TrajectoryPlannerROS:
  acc_lim_theta: 0.1
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  angular_sim_granularity: 0.05
  dwa: false
  escape_reset_dist: 0.1
  escape_reset_theta: 1.5707963267948966
  escape_vel: -0.05
  goal_distance_bias: 1
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.1
  holonomic_robot: true
  max_vel_theta: 0.2
  max_vel_x: 0.2
  min_in_place_vel_theta: 0.2
  min_vel_theta: -0.05
  min_vel_x: 0.05
  min_vel_y: 0.05
  occdist_scale: 0.01
  oscillation_reset_dist: 0.1
  path_distance_bias: 0.4
  restore_defaults: false
  sim_granularity: 0.05
  sim_time: 1.0
  simple_attractor: false
  vtheta_samples: 20
  vx_samples: 20
  y_vels: -0.3,-0.1,0.1,-0.3
aggressive_reset:
  reset_distance: 1.84
base_frame: base_footprint
base_global_planner: navfn/NavfnROS
base_local_planner: base_local_planner/TrajectoryPlannerROS
clearing_rotation_allowed: false
conservative_reset:
  reset_distance: 3.0
conservative_reset_dist: 3.0
controller_frequency: 30.0
controller_patience: 5.0
global_costmap:
  footprint: '[]'
  footprint_padding: 0.01
  global_frame: map
  height: 10
  inflater:
    cost_scaling_factor: 10.0
    enabled: true
    inflate_unknown: false
    inflation_radius: 0.1
    robot_radius: 0.3
  obstacles:
    base_scan:
      clearing: true
      data_type: LaserScan
      marking: true
      max_obstacle_height: 0.3
      min_obstacle_height: 0.1
      obstacle_range: 6.0
      raytrace_range: 10.0
      topic: hsrb/base_scan
    combination_method: 1
    enabled: true
    footprint_clearing_enabled: true
    head_xtion:
      clearing: true
      data_type: PointCloud2
      marking: true
      max_obstacle_height: 1.0
      min_obstacle_height: 0.05
      obstacle_range: 6.0
      raytrace_range: 10.0
      topic: hsrb/head_rgbd_sensor/depth_registered/rectified_points
    max_obstacle_height: 2.0
    observation_sources: base_scan
    obstacle_range: 2.5
  origin_x: 0.0
  origin_y: 0.0
  plugins:
  - name: static_map
    type: costmap_2d::StaticLayer
  - name: obstacles
    type: costmap_2d::ObstacleLayer
  - name: inflater
    type: costmap_2d::InflationLayer
  publish_frequency: 0.0
  resolution: 0.05
  robot_base_frame: base_link
  robot_radius: 0.3
  static_map:
    enabled: true
  transform_tolerance: 0.5
  update_frequency: 5.0
  width: 10
local_costmap:
  footprint: '[]'
  footprint_padding: 0.01
  global_frame: odom
  height: 4
  inflater:
    cost_scaling_factor: 10.0
    enabled: true
    inflate_unknown: false
    inflation_radius: 0.1
    robot_radius: 0.3
  obstacles:
    base_scan:
      clearing: true
      data_type: LaserScan
      marking: true
      max_obstacle_height: 0.3
      min_obstacle_height: 0.1
      obstacle_range: 6.0
      raytrace_range: 10.0
      topic: hsrb/base_scan
    combination_method: 1
    enabled: true
    footprint_clearing_enabled: true
    head_xtion:
      clearing: true
      data_type: PointCloud2
      marking: true
      max_obstacle_height: 1.0
      min_obstacle_height: 0.05
      obstacle_range: 6.0
      raytrace_range: 10.0
      topic: hsrb/head_rgbd_sensor/depth_registered/rectified_points
    max_obstacle_height: 2.0
    observation_sources: base_scan
    obstacle_range: 2.5
  origin_x: 0.0
  origin_y: 0.0
  plugins:
  - name: obstacles
    type: costmap_2d::ObstacleLayer
  - name: inflater
    type: costmap_2d::InflationLayer
  publish_frequency: 2.0
  resolution: 0.05
  robot_base_frame: base_link
  robot_radius: 0.3
  rolling_window: true
  transform_tolerance: 0.5
  update_frequency: 5.0
  width: 4
make_plan_add_unreachable_goal: true
make_plan_clear_costmap: true
max_planning_retries: -1
navigation_log_record_service_name: navigation_log_recorder/record
oscillation_distance: 0.5
oscillation_timeout: 10.0
planner_frequency: 0.0
planner_patience: 1.0
planning_timeout: 20.0
record_parameter_node_names:
- base_path_planner
- omni_path_follower

restore_defaults: false
shutdown_costmaps: false
# Goal tolerance settings
xy_goal_tolerance: 0.1
yaw_goal_tolerance: 0.1
latch_xy_goal_tolerance: true




# Costmap settings
inflation_radius: 0.1
obstacle_range: 2.5